// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALicaThVYZx9S_gYzGUt0MZmd1iPCO0-c',
    appId: '1:80007197846:web:28ad22b1563cec0036feb7',
    messagingSenderId: '80007197846',
    projectId: 'homeapp-6e597',
    authDomain: 'homeapp-6e597.firebaseapp.com',
    storageBucket: 'homeapp-6e597.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA0FVMi4i0Bd0RC9SyWliKz9B3MO8Y5GQ',
    appId: '1:80007197846:android:3a09b6367d1afb4336feb7',
    messagingSenderId: '80007197846',
    projectId: 'homeapp-6e597',
    storageBucket: 'homeapp-6e597.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMLiQA4VrZFji_MEGv0i7gnNsxQUYhkrg',
    appId: '1:80007197846:ios:b0c9797f430d5ba536feb7',
    messagingSenderId: '80007197846',
    projectId: 'homeapp-6e597',
    storageBucket: 'homeapp-6e597.firebasestorage.app',
    iosBundleId: 'com.example.homeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMLiQA4VrZFji_MEGv0i7gnNsxQUYhkrg',
    appId: '1:80007197846:ios:b0c9797f430d5ba536feb7',
    messagingSenderId: '80007197846',
    projectId: 'homeapp-6e597',
    storageBucket: 'homeapp-6e597.firebasestorage.app',
    iosBundleId: 'com.example.homeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALicaThVYZx9S_gYzGUt0MZmd1iPCO0-c',
    appId: '1:80007197846:web:19286932400796ff36feb7',
    messagingSenderId: '80007197846',
    projectId: 'homeapp-6e597',
    authDomain: 'homeapp-6e597.firebaseapp.com',
    storageBucket: 'homeapp-6e597.firebasestorage.app',
  );
}
